DROP TABLE IF EXISTS `resources`;

CREATE TABLE `resources` (
  `name` varchar(50) NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(140) NOT NULL,
  `link` varchar(300) NOT NULL,
  `category` varchar(50) NOT NULL,
  `platform` varchar(50) DEFAULT NULL,
  `slug` varchar(50) NOT NULL,
  `path` varchar(50) NOT NULL,
  `image` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `resources` WRITE;
/*!40000 ALTER TABLE `resources` DISABLE KEYS */;

INSERT INTO `resources` (`name`, `id`, `description`, `link`, `category`, `platform`, `slug`, `path`, `image`)
VALUES
	('Bret Mayer\'\'s Kanji Resource',1,'Kanji resources for structured practice and lists.','http://www.bretmayer.com/kanji.html','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Genkoyoushi Paper Generator',2,'Create manuscript paper for kanji practice.','https://www.incompetech.com/graphpaper/genkoyoushi/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Hinoki Project',3,'Computational linguistics and vocabulary learning.','https://hinoki-project.org/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Japanese Graph',4,'Practice kanji and vocabulary with visualizations.','https://japanesegraph.com/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Kanji by Stroke Order',5,'Learn kanji stroke order through writing practice.','https://kanji.sljfaq.org/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Kanji Practice',6,'Interactive platform for kanji and vocabulary.','https://kanjipractice.com/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Kanjipedia',7,'Comprehensive kanji dictionary with examples.','https://www.kanjipedia.jp/howto/about.html','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Koohii Kanji Review',8,'Community-driven kanji and vocabulary learning.','https://kanji.koohii.com/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Kotoba no Gakko',9,'Vocabulary acquisition and insights.','https://site.kotobanogakko.com/special/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('KotobaBot',10,'Chatbot for practicing vocabulary.','https://kotobaweb.com/bot','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Kotowaza',11,'Learn proverbs and cultural insights.','https://kotowaza.co.uk/index.php','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Kurumi Kanji Search',12,'Kanji search tool to build vocabulary.','https://kurumi.com/jp/kjbh/?k=%E6%9C%AC','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Mainichi Kanji',13,'Daily kanji practice to build vocabulary.','https://mainichikanji.com/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Niai - Similar Vocabulary',14,'Explore similar words.','https://niai.mrahhal.net/similar','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Nippon Colors',15,'Traditional Japanese color meanings','https://nipponcolors.com/','Vocabulary & Kanji','','vocabulary-kanji','vocabulary',NULL),
	('OniKanji',16,'Master kanji naturally with context-based learning systeme','https://onikanji.com/','Vocabulary & Kanji','','vocabulary-kanji','vocabulary',NULL),
	('Shared Anki Decks',17,'Anki decks for vocabulary and kanji.','https://ankiweb.net/shared/info/457148655?cb=1717343711197','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('WaniKani',18,'Learn kanji and vocabulary with mnemonics.','https://www.wanikani.com/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Wikibooks Linguistics Vocabulary',19,'Vocabulary list for linguistics terms.','https://en.m.wikibooks.org/wiki/Japanese/Vocabulary/Linguistics','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('Yomikatawa',20,'Learn vocabulary and kanji readings.','https://yomikatawa.com/','Vocabulary & Kanji',NULL,'vocabulary-kanji','vocabulary',NULL),
	('DeepL Translator',21,'Accurate translations between languages.','https://www.deepl.com/en/translator#','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('GeekyDic',22,'User-friendly online dictionary.','https://emilekroeger.github.io/geekydic/app/index.html#/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Goo Dictionary',23,'Comprehensive dictionary with examples.','https://dictionary.goo.ne.jp/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Jisho',24,'Powerful dictionary with detailed explanations.','http://www.jisho.org/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Jisho (Hlorenzi)',25,'Alternative Jisho interface with added features.','https://jisho.hlorenzi.com/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Jitenon Kanji Dictionary',26,'Kanji dictionary with detailed character breakdowns.','https://kanji.jitenon.jp/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('JLect',27,'Explore dialects and regional vocabulary.','https://www.jlect.com/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Jotoba',28,'Multilingual dictionary with context.','https://jotoba.de/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Kanjisho',29,'Kanji-focused dictionary with readings and stroke order.','https://www.kanjisho.com/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Kotobank',30,'Dictionary aggregator with multiple sources.','https://kotobank.jp/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Onomato Project',31,'Explore onomatopoeia with examples.','https://onomatoproject.com/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('PokeJisho',32,'Pokémon-themed dictionary.','https://www.pokejisho.com/en/jisho/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Takoboto',33,'Offline dictionary with kanji lookup.','https://takoboto.jp/','Dictionaries Apps',NULL,'dictionaries-apps','applications',NULL),
	('Weblio Thesaurus',34,'Find synonyms and related words.','https://thesaurus.weblio.jp/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Yomitan',35,'Translate text on webpages easily.','https://github.com/themoeway/yomitan','Dictionaries Apps',NULL,'dictionaries-apps','applications',NULL),
	('Aedict',36,'Comprehensive dictionary app.','http://aedict.eu/','Dictionaries Apps',NULL,'dictionaries-apps','applications',NULL),
	('Kanji Benkyō',37,'Learn kanji with this app.','https://apps.apple.com/us/app/learn-japanese-kanji-benky%C5%8D/id1541592138?ct=https%3A%2F%2Findiecatalog.app','Dictionaries Apps',NULL,'dictionaries-apps','applications',NULL),
	('Shirabe Jisho',38,'Dictionary app with kanji lookup.','https://apps.apple.com/app/shirabe-jisho/id1005203380','Dictionaries Apps',NULL,'dictionaries-apps','applications',NULL),
	('DJT Grammar Guide',39,'Extensive guide covering grammar in depth.','https://djtarchive.neocities.org/bunpou/full_day','Grammar',NULL,'grammar','grammar',NULL),
	('Edewakaru',40,'Detailed explanations of grammar points.','https://www.edewakaru.com/','Grammar',NULL,'grammar','grammar',NULL),
	('Guide to Japanese',41,'Your go-to guide for grammar and basics.','https://guidetojapanese.org/learn/','Grammar',NULL,'grammar','grammar',NULL),
	('IMABI',42,'Detailed grammar lessons for all levels.','https://www.imabi.org/','Grammar',NULL,'grammar','grammar',NULL),
	('JLPT Grammar List',43,'Comprehensive list of JLPT grammar points.','https://jlptgrammarlist.neocities.org/','Grammar',NULL,'grammar','grammar',NULL),
	('Kanji-Link',44,'Learn grammar and kanji with quizzes.','https://www.kanji-link.com/fr/#','Grammar',NULL,'grammar','grammar',NULL),
	('Maggie Sensei',45,'Friendly lessons on grammar points.','https://maggiesensei.com/','Grammar',NULL,'grammar','grammar',NULL),
	('Minato JF',46,'Online courses and resources, including grammar lessons.','https://minato-jf.jp/','Grammar',NULL,'grammar','grammar',NULL),
	('Sakubi',47,'Minimalist guide to essential grammar.','https://sakubi.neocities.org/','Grammar',NULL,'grammar','grammar',NULL),
	('Tanos JLPT Resources',48,'Grammar lists and practice materials for the JLPT.','http://www.tanos.co.uk/jlpt/','Grammar',NULL,'grammar','grammar',NULL),
	('Dokusho Club',49,'Reading club for learners.','https://dokushoclub.com/','Reading',NULL,'reading','reading',NULL),
	('Learn Natively',50,'Find books for your reading level.','https://learnnatively.com/','Reading',NULL,'reading','reading',NULL),
	('Mangaz',51,'Read manga online.','https://www.mangaz.com/','Reading',NULL,'reading','reading',NULL),
	('Master List of Book Clubs',52,'A master list of books going from absolute beginner to advanced learner','https://community.wanikani.com/t/master-list-of-book-clubs/35283','Reading',NULL,'reading','reading',NULL),
	('Satori Reader',53,'Read and listen to stories.','https://www.satorireader.com/','Reading',NULL,'reading','reading',NULL),
	('Sōseki Project',54,'A collection of the author Natsume Sōseki\'\'s work.','https://www.sosekiproject.org/#','Reading','','reading','reading',NULL),
	('Tadoku',55,'Free graded readers for learners.','https://tadoku.org/japanese/en/free-books-en/','Reading',NULL,'reading','reading',NULL),
	('Yomimono Ippai',56,'Lots of books to read for every level','http://www17408ui.sakura.ne.jp/tatsum/project/Yomimono/Yomimono-ippai/index.html','Reading',NULL,'reading','reading',NULL),
	('YomuJP',57,'Read texts with translations.','https://yomujp.com/','Reading',NULL,'reading','reading',NULL),
	('YomuYomu',58,'Read books online.','https://yomuyomu.app/','Reading',NULL,'reading','reading',NULL),
	('Manabi Reader',59,'A solid app for reading sentences, read ebooks and listen to audios.','https://reader.manabi.io/','Apps',NULL,'reading','reading',NULL),
	('Mihon',60,'Manga reader app.','https://mihon.app/','Apps',NULL,'reading','reading',NULL),
	('Voracious',61,'Improve reading and listening skills.','https://voracious.app/','Apps',NULL,'reading','reading',NULL),
	('Free Japanese Font',62,'Download free fonts.','https://www.freejapanesefont.com/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Google Sheets JLPT',63,'Comprehensive JLPT study resources.','https://docs.google.com/spreadsheets/d/15ELElkomfixdS4-dNrpxrNl14mlJUZrdD0h7N6iEE2k/edit?gid=1386920750#gid=1386920750','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Japanese Discord',64,'Join the community for language practice.','https://discord.gg/japanese','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Japanese Wiki',65,'Explore various topics.','https://www.japanesewiki.com/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Kaiwa Kai',66,'Practice conversation skills.','https://www.kaiwakai.com/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Kuzuri Resources',67,'Collection of useful resources.','https://kuzuri.neocities.org/resources','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('LangPractice',68,'Language practice platform.','https://langpractice.com/japanese/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Learn Japanese Reddit',69,'Community for learners.','https://www.reddit.com/r/LearnJapanese/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Rondely English Terms',70,'Glossary of English terms.','https://rondely.com/EigoYogo/irir/iti.htm','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('SuperNative',71,'Improve listening skills.','https://supernative.tv/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('The Moe Way',72,'An amazing guide with tips ','https://learnjapanese.moe/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Unagibun JLPT Online',73,'Online resources for JLPT preparation.','https://www.unagibun.com/jlpt-online/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Kana Dojo',74,'KanaDojo is a fun, minimalist, aesthetic platform for learning and practicing Japanese online.','https://kanadojo.com','Kana',NULL,'kana','vocabulary',NULL),
	('Kana Pro',75,'Practice your hiragana and katakana.','https://kana.pro','Kana',NULL,'kana','vocabulary',NULL),
	('Real Kana',76,'Study your kana with the possibility to choose between multiple fonts.','https://realkana.com','Kana',NULL,'kana','vocabulary',NULL),
	('Akane Japanese Class',77,'Effective and beginner-friendly Japanese lessons.','https://www.youtube.com/@Akane-JapaneseClass/','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/d85bb43d-a668-413f-83ad-d22693f02a03.jpg'),
	('CI Japanese',78,'Comprehensible input for Japanese learners.','https://www.youtube.com/@cijapanese','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/e0f45662-ec4d-4a04-b1df-773ec6429768.jpg'),
	('Dogen',79,'Japanese language learning with a comedic twist.','https://www.youtube.com/@Dogen','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/76399ea0-eed3-420a-b11b-dfa84d7959e8.jpg'),
	('Japanese Ammo with Misa',80,'Comprehensive Japanese lessons for all levels.','https://www.youtube.com/@JapaneseAmmowithMisa','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/9eeba09f-98d3-486a-b53d-cdc75f63856b.jpg'),
	('Japanese with Shun',81,'Simple and effective Japanese language lessons.','https://www.youtube.com/@JapanesewithShun','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/6b8aeee9-f179-4019-a4b0-98ee7cdfd717.jpg'),
	('Japanese with Taka',82,'Master Japanese with Taka\'\'s focused lessons.','https://www.youtube.com/@JapanesewithTaka','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/21c8daac-3bde-4c2d-9aff-ba471a35d9ba.jpg'),
	('Japasuta',83,'Interactive Japanese language tutorials.','https://www.youtube.com/@japasuta','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/c2ecabe8-e935-4158-adf2-cdf3bb58f21a.jpg'),
	('Meshclass',84,'Learn Japanese through fun and interactive lessons.','https://www.youtube.com/@meshclass','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/4025ac12-6487-4f3d-9ffe-5dd6d284cabf.jpg'),
	('Miku Real Japanese',85,'Practical and real-life Japanese learning.','https://www.youtube.com/@mikurealjapanese','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/02649d85-7886-40fc-92f3-46ab25bf4189.jpg'),
	('Necota\'\'s Japanese Language Class',86,'Creative lessons for mastering Japanese.','https://www.youtube.com/@necotasjapaneselanguagecla291','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/e7c82a95-198f-43bc-bb59-3228fe942d9a.jpg'),
	('Nihongo no Mori',87,'Learn Japanese grammar and vocabulary effectively.','https://www.youtube.com/@nihongonomori2013','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/5331a389-d720-4097-9f31-9e0f201b38e0.jpg'),
	('Onomappu',88,'Learn Japanese through natural expressions and phrases.','https://www.youtube.com/@Onomappu/','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/26d78526-5f7a-42ed-8fb5-6a39b020cb45.jpg'),
	('Sambonjuku',89,'Fun and engaging Japanese lessons for learners.','https://www.youtube.com/@sambonjuku/','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/51c7e587-a8db-4814-9e36-78762f5cf9e6.jpg'),
	('Sayuri Saying',90,'Practical and fun Japanese language tutorials.','https://www.youtube.com/@SayuriSaying','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/a879e1a3-5439-4d6d-8d60-e161c571023c.jpg'),
	('Tanaka San',91,'Learn Japanese with practical conversations and tips.','https://www.youtube.com/@japanese_tanakasan','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/5aeb279c-b4b8-4b8a-8fef-3c57befb642e.jpg'),
	('Archipel Documentaries',92,'Deep dive into Japanese culture and tradition through documentaries.','https://www.youtube.com/@ArchipelDocumentaries','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/f59e9b0c-fc9e-492e-b49f-116f334bdf92.jpg'),
	('Bappa Shota',93,'Japanese vlogger who has been traveling the world since 2011','https://www.youtube.com/@BappaShota','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/a27c10e8-0058-4859-ac19-aeccaf37c764.jpg?height=150&width=150'),
	('Koto Labo',94,'Insights into Japanese music and traditional instruments.','https://www.youtube.com/@kotolabo','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/b6d30567-06bd-4d00-8254-976d74e9dad8.jpg'),
	('Osho Taigu',95,'Explore Japanese traditions and Zen teachings.','https://www.youtube.com/@osho_taigu/','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/be5a1326-fc18-4f04-9c11-ff386428d6d7.jpg'),
	('Burihhiiinews Channel',96,'Stay updated with Japanese news and cultural insights.','https://www.youtube.com/@burihhiiiinewschannel','Entertainment','youtube','entertainment','media','https://cloud.tareqitos.me/i/f58c21eb-c837-42f9-af41-ef9afd6d38b2.jpg'),
	('Cocoro Kase',97,'Engaging lessons and insights focused on language and cultural nuances.','https://www.youtube.com/@cocoro_kase','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/dd11fcff-2253-4d1d-8e0b-2eef1a9b2493.jpg'),
	('EASY JAPANESE',98,'Simplified and accessible language lessons with practical examples.','https://www.youtube.com/@EASYJAPANESE','Podcast','youtube','podcast','podcast','https://cloud.tareqitos.me/i/97cf5176-be71-4a56-9c47-e3cf3fbae773.jpg'),
	('Nihongo Con Teppei',99,'Podcast for beginner on how to speak the language naturally.','https://open.spotify.com/show/4W4jYoKRmjlURKO1fIfcOK?si=53534ca1bd654ffd','Podcast','spotify, youtube','podcast','podcast','https://cloud.tareqitos.me/i/f5d98ed5-9d5d-40a7-823d-81e11f6758bf.jpg?height=100&width=100&quality=50'),
	('Oyasumi Japanese with Shun',100,'Easy Japanese using Genki (N5-N4) grammar. This is perfect to listen before you go to sleep.','https://open.spotify.com/show/7x4JCyDeWR60kzJXoOBTrQ','Podcast','spotify','podcast','podcast','https://cloud.tareqitos.me/i/10d34001-1ee0-4773-9c50-5e170a519a82.jpg?height=150&width=150'),
	('The Bite Size Japanese Podcast',101,'A podcast about daily life for improving your listening skills','https://open.spotify.com/show/58H68tM3uC2JNZI4hXvdeu','Podcast','spotify','podcast','podcast','https://cloud.tareqitos.me/i/6a10d710-6f8c-41c4-b36e-384784a08748.jpg?height=150&width=150'),
	('The Miku Real Japanese',102,'Miku shares insights into daily life and culture.','https://open.spotify.com/show/6Nl8RDfPxsk4h4bfWe76Kg?si=48aec8e2d5234a98','Podcast','spotify','podcast','podcast','https://cloud.tareqitos.me/i/d945d521-c56f-43da-972a-8386260670f2.jpg?height=150&width=150'),
	('Game Nantoka / ゲームなんとか',103,'Podcast of friends casually talking about games.','https://open.spotify.com/show/0VpJSbTokWLLJ0zppnbrlM?si=13ab080d6e7f4dbe','Science & Technology','spotify','science-technology','podcast','https://cloud.tareqitos.me/i/1a81d385-dfca-40da-aea0-5133f3c1beac.jpg?height=150&width=150'),
	('KIYOi / キヨ。',104,'Dynamic gaming streams, reviews, and humorous commentary.','https://www.youtube.com/@KIYOisGOD','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/80e37a5c-f9b4-4f6d-b479-4391cffc8511.jpg'),
	('Kojiseto Games',105,'Entertaining gaming content with commentary on various popular titles.','https://www.youtube.com/@KojisetoGames','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/c18df950-aea4-47df-8422-dbcccb81a605.jpg'),
	('Senakuma Desu',106,'Fun and creative videos that explore casual and everyday topics.','https://www.youtube.com/@senakumadesu','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/cfc78559-4f1a-4c53-8995-241d879052bd.jpg'),
	('Sora Sakurai',107,'Official channel of Masahiro Sakurai, creator of Kirby and Super Smash Bros.','https://www.youtube.com/@sora_sakurai_jp','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/468ce1be-a0cd-499b-949f-03b3ce7930b0.jpg'),
	('Tetsuo/てつお ',108,'Channel focused on the Dragon Quest video games series.','https://www.youtube.com/@ch-mj8xi','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/b1d092f6-3ede-4c1b-8da5-f89bad292a32.jpg'),
	('Anki',109,'Powerful flashcard app for studying.','https://apps.ankiweb.net/','Flashcards',NULL,'flashcards','applications',NULL),
	('Quizlet',110,'Study with flashcards and games.','https://quizlet.com/','Flashcards',NULL,'flashcards','applications',NULL),
	('Renshuu',111,'Practice vocabulary and grammar.','https://www.renshuu.org/','Flashcards',NULL,'flashcards','applications',NULL),
	('Ringotan',112,'Learn kanji with mnemonics.','https://www.ringotan.com/','Flashcards',NULL,'flashcards','applications',NULL),
	('Smouldering Durtles',113,'An android client application for WaniKani','https://play.google.com/store/apps/details?id=com.smouldering_durtles.wk&hl=en-US','Flashcards',NULL,'flashcards','applications',NULL),
	('Bunpro',114,'Grammar study platform.','https://bunpro.jp/','Grammar & Kana',NULL,'grammar-kana','applications',NULL),
	('Kana',115,'Learn hiragana and katakana.','https://apps.apple.com/us/app/kana-hiragana-and-katakana/id1454200955?ct=https%3A%2F%2Findiecatalog.app','Grammar & Kana',NULL,'grammar-kana','applications',NULL),
	('Genkoyoushi',116,'Japanese character graph generator','https://www.incompetech.com/graphpaper/genkoyoushi/','Tools',NULL,'tools','applications',NULL),
	('Hanabi',117,'A powerful subtitle parser for Youtube using AI','https://hanabira.org/','Tools',NULL,'tools','applications',NULL),
	('Jimaku',118,'A list of subtitles files for anime, drama and movies.','https://jimaku.cc','Tools',NULL,'tools','applications',NULL),
	('Kaku',119,'Handwriting recognition app.','https://kaku.fuwafuwa.ca/','Tools',NULL,'tools','applications',NULL),
	('Sensei',120,'Learn with interactive lessons.','https://apps.apple.com/us/app/learn-japanese-sensei/id1495789984?ct=https%3A%2F%2Findiecatalog.app','Tools',NULL,'tools','applications',NULL),
	('AFK Arena',121,'Adventure / Arena game','https://play.google.com/store/apps/details?id=com.lilithgame.hgame.gp','Mobile','','mobile','games',NULL),
	('Aggretsuko: Match 3',122,'Puzzle game based on the popular Netflix animation series','https://play.google.com/store/apps/details?id=com.hive.aggretsuko','Mobile','','mobile','games',NULL),
	('ALTER EGO',123,'Game about literature and psychology','https://play.google.com/store/apps/details?id=com.caracolu.alterego','Mobile','','mobile','games',NULL),
	('Animal crossing: Pocket Camp',124,'Build your camp with furnitures','https://play.google.com/store/apps/details?id=com.nintendo.zaca','Mobile','','mobile','games',NULL),
	('Any Kairosoft game',125,'Strategy game in a RPG style','https://play.google.com/store/apps/dev?id=7710637777904825280','Mobile','','mobile','games',NULL),
	('AZNANA',126,'Narrative game','https://play.google.com/store/apps/details?id=com.caracolu.aznana','Mobile','','mobile','games',NULL),
	('BanG Dream!',127,'Popular rythm game with original and anime covered songs','https://play.google.com/store/apps/details?id=com.bushiroad.en.bangdreamgbp','Mobile','','mobile','games',NULL),
	('Bear\'\'s Restaurant',128,'Manage a restaurant for the dead people and animals','https://play.google.com/store/apps/details?id=com.rpgsnack.bearsrestaurant','Mobile','','mobile','games',NULL),
	('Cats & Soup',129,'Cook with cats and prepare delicious soups','https://play.google.com/store/apps/details?id=com.hidea.cat','Mobile','','mobile','games',NULL),
	('Fishing paradiso',130,'A narrative game with a moving scenario','https://play.google.com/store/apps/details?id=com.rpgsnack.fishingparadise','Mobile','','mobile','games',NULL),
	('her tears were my light',131,'A love story between time and space','https://play.google.com/store/apps/details?id=com.nomnomnami.hertearsweremylight','Mobile','','mobile','games',NULL),
	('Hungry hearts diner',132,'Manage a Japanese restaurant and bond with your clients','https://play.google.com/store/apps/details?id=jp.co.gagex.orionEN','Mobile','','mobile','games',NULL),
	('Love is in small things',133,'A cozy art game','https://play.google.com/store/apps/details?id=com.lunosoft.puuung1','Mobile','','mobile','games',NULL),
	('Snowman Story',134,'Follow the story of a snowman who doesn\'\'t want to melt','https://play.google.com/store/apps/details?id=com.rpgsnack.snowman','Mobile','','mobile','games',NULL),
	('Sumikkogurashi farm',135,'Relaxing farming game','https://play.google.com/store/apps/details?id=jp.co.imagineer.sumikkogurashi.farm','Mobile','','mobile','games',NULL),
	('Tsuki\'\'s Oddysey',136,'A passive adventure game','https://play.google.com/store/apps/details?id=com.hyperbeard.odyssey','Mobile','','mobile','games',NULL),
	('Vanished anniversary',137,'Visual novel with five unique stories','https://play.google.com/store/apps/details?id=com.abocado.abocado','Mobile','','mobile','games',NULL),
	('ねこあつめ',138,'Tamagochi game with a cat','https://play.google.com/store/apps/details?id=jp.co.hit_point.nekoatsume','Mobile','','mobile','games',NULL),
	('旅かえる',139,'A game about a Frog that goes on many journeys','https://play.google.com/store/apps/details?id=jp.co.hit_point.tabikaeru','Mobile','','mobile','games',NULL),
	('unityroom',140,'A list of Unity-made games playable in browser','https://unityroom.com/','Web','','web','games',NULL),
	('Monosugoi Zukan',141,'NHK’s interactive animal book with 3D views, quizzes, and facts.','https://www.nhk.or.jp/school/zukan/','General',NULL,'general','encyclopedia',NULL),
	('Ikimonopedia',142,'Large web animal encyclopedia with photos, videos, and species facts.','https://ikimonopedia.com/','General',NULL,'general','encyclopedia',NULL),
	('Digital Dialects: Animals 1',143,'Beginner game to learn animal words with audio and simple quizzes.','https://www.digitaldialects.com/Japanese/dobutsu.htm','Study / Games',NULL,'study-games','encyclopedia',NULL),
	('Digital Dialects: Animals 2',144,'Next-step practice for animal vocabulary with listening tasks.','https://www.digitaldialects.com/Japanese/dobutsu2.htm','Study / Games',NULL,'study-games','encyclopedia',NULL),
	('Forest Creatures — Mammals',145,'Photo-based guide to mammals living in Tokyo Gas’s forest sites.','https://www.tokyo-gas.co.jp/env/forest/dictionary/mammal/index.html','Mammals',NULL,'mammals','encyclopedia',NULL),
	('Japanese Bird Encyclopedia',146,'Species pages with photos, calls, ranges, and identification tips.','https://www.suntory.co.jp/eco/birds/encyclopedia/','Birds',NULL,'birds','encyclopedia',NULL),
	('BIRD FAN: Wild Bird Guide',147,'Wild Bird Society guide with searchable lists and call samples.','https://www.birdfan.net/pg/kind/','Birds',NULL,'birds','encyclopedia',NULL),
	('Bird Photo Index',148,'Photo catalog of birds observed around Chiba and nearby areas.','https://chibadai.flier.jp/bird/html/syasin.html','Birds',NULL,'birds','encyclopedia',NULL),
	('Dinosaur Encyclopedia',149,'Species index by the Fukui Prefectural Dinosaur Museum.','https://www.dinosaur.pref.fukui.jp/dino/dic/','Dinosaurs',NULL,'dinosaurs','encyclopedia',NULL),
	('Chōgyo Zukan — Game Fish',150,'Angler-focused fish profiles with practical notes and tips.','http://www.daiwa.globeride.jp/pictorial/','Sea & Fish',NULL,'sea-fish','encyclopedia',NULL),
	('Sakana Zukan',151,'Searchable fish index with hazards, habitat, and usage notes.','https://fishai.jp/','Sea & Fish',NULL,'sea-fish','encyclopedia',NULL),
	('Poisonous Fish Guide',152,'Overview of toxic and venomous fish with identification points.','https://fishai.jp/poison','Sea & Fish',NULL,'sea-fish','encyclopedia',NULL),
	('Toshitoshi Web Fish Encyclopedia',153,'Fish photos shot at aquariums across Japan with brief notes.','https://toshitoshi.jp/fish/','Sea & Fish',NULL,'sea-fish','encyclopedia',NULL),
	('Toshitoshi Web Aquarium',154,'Photo tours and highlights from aquariums nationwide.','https://toshitoshi.jp/aqua/','Sea & Fish',NULL,'sea-fish','encyclopedia',NULL),
	('Chirimon Encyclopedia',155,'Identify tiny sea creatures found in dried young sardines.','http://www.chirimon.jp/','Sea & Fish',NULL,'sea-fish','encyclopedia',NULL),
	('Evolving Insect Encyclopedia',156,'Broad photo index of insects organized by order and family.','http://www.ha.shotoku.ac.jp/~kawa/KYO/SEIBUTSU/DOUBUTSU/500KonchuTop/','Insects & Arachnids',NULL,'insects-arachnids','encyclopedia',NULL),
	('Spider Encyclopedia',157,'Common spiders with clear photos and concise descriptions.','https://www.insects.jp/konbunkumo.htm','Insects & Arachnids',NULL,'insects-arachnids','encyclopedia',NULL),
	('Aquatic Insects Photo Index',158,'Macro photos and IDs for freshwater aquatic insects.','https://www.eonet.ne.jp/~suiseikontyu/','Insects & Arachnids',NULL,'insects-arachnids','encyclopedia',NULL),
	('Larvae Encyclopedia',159,'Photo catalog specializing in insect larvae across orders.','http://aoki2.si.gunma-u.ac.jp/youtyuu/','Insects & Arachnids',NULL,'insects-arachnids','encyclopedia',NULL),
	('Household Pest Encyclopedia',160,'Traits and control methods for pests in and around homes.','http://www.imamuranet.com/hp/hphp/hp.html','Insects & Arachnids',NULL,'insects-arachnids','encyclopedia',NULL),
	('Earth Pest Encyclopedia',161,'Pest biology and control advice by Earth Corporation.','https://www.earth.jp/gaichu/index.html','Insects & Arachnids',NULL,'insects-arachnids','encyclopedia',NULL),
	('sci.lang.japan',162,'Clear list of kanji radicals with Japanese names and explanations.','http://www.sljfaq.org/afaq/radical-names.html','Radicals',NULL,'radicals','vocabulary',NULL),
	('Kanji Alive',163,'Overview of the 214 traditional Kangxi radicals with meanings.','https://kanjialive.com/214-traditional-kanji-radicals/','Radicals',NULL,'radicals','vocabulary',NULL),
	('Gaoshukai',164,'Japanese-language guide explaining radicals and their usage.','https://www.gaoshukai.com/20/07/0004/','Radicals',NULL,'radicals','vocabulary',NULL),
	('Kanji Radicals - Wikipedia',165,'Reference article explaining kanji radicals, history, and classification.','https://en.wikipedia.org/wiki/Kanji_radical','Radicals',NULL,'radicals','vocabulary',NULL),
	('OK! Cozy up! (飯田浩司のOK! Cozy up！)',166,'Daily Japanese news talk show with commentary and guest opinions.','https://www.1242.com/cozy/','News','apple,spotify','news','podcast','https://cloud.tareqitos.me/i/2543bc8a-8b85-4292-a751-c1fcb8599a5d.jpg'),
	('Asahi News Podcast (朝日新聞 ニュースの現場から)',167,'In-depth reporting and analysis by Asahi Shimbun journalists.','https://www.asahi.com/special/podcasts/','News','apple,spotify','news','podcast','https://cloud.tareqitos.me/i/6a3e20d9-b372-458f-8763-c4ea1a1e5fa1.jpg'),
	('NewsPicks Talk Room (NewsPicks Talk Room)',168,'Business, tech, and social topics discussed by NewsPicks editors.','https://podcasts.apple.com/jp/podcast/newspicks-talk-room/id1522306711?l=en-US','News','apple,spotify','news','podcast','https://cloud.tareqitos.me/i/27e9511c-285e-45a2-8d02-aa54ef45c4b3.jpg'),
	('Ogiue Chiki Session (荻上チキ・Session)',169,'Daily current affairs podcast with critical analysis and interviews.','https://www.tbsradio.jp/ss954/','News','apple,spotify','news','podcast','https://cloud.tareqitos.me/i/90c59e25-565a-45fb-8e36-cdbedd9d31b1.jpg'),
	('Machida Tetsu no Fukabori (町田徹のふかぼり！)',170,'Weekly deep dives into Japanese economic and political news.','https://www.radionikkei.jp/podcast/fukabori/','News','apple,spotify','news','podcast','https://cloud.tareqitos.me/i/0ad97e2a-b196-4431-b141-715326303c8e.jpg?width=200'),
	('Iida Koji The Daily News (飯田浩司 The Daily News)',171,'Condensed daily news updates hosted by Koji Iida.','https://podcasts.apple.com/jp/podcast/%E9%A3%AF%E7%94%B0%E6%B5%A9%E5%8F%B8-the-daily-news/id1507288239','News','apple,spotify','news','podcast','https://cloud.tareqitos.me/i/7ff23b45-5fad-427a-9aee-5843376e7d4f.jpg'),
	('SBS Japanese (SBS日本語放送)',172,'Japanese-language news and features from Australia’s SBS.','https://www.sbs.com.au/language/japanese/','News','apple,spotify,youtube','news','podcast','https://cloud.tareqitos.me/i/26550fce-cfd0-4ba5-8a36-0234f72d164e.jpg'),
	('Rebuild',205,'Japanese tech podcast on software, gadgets, and developer talk.','https://rebuild.fm/','Science & Technology','apple,spotify','science-technology','podcast','https://cloud.tareqitos.me/i/a363d334-5f38-49b6-89b6-0076f7f77b10.jpg?width=200'),
	('Goryugocast (ごりゅごcast)',206,'Tech tips and tools to make work and life easier.','https://podcasts.apple.com/us/podcast/%E3%81%94%E3%82%8A%E3%82%85%E3%81%94cast/id1373668452','Science & Technology','apple,spotify','science-technology','podcast','https://cloud.tareqitos.me/i/caf4dc4f-a1a0-4d80-95c8-94277bd394db.jpg'),
	('Weekly Nikkei Trendy & Cross Trend',207,'Weekly bite-size trend and business keywords from editors.','https://podcasts.apple.com/jp/podcast/%E9%80%B1%E5%88%8A-%E6%97%A5%E7%B5%8C%E3%83%88%E3%83%AC%E3%83%B3%E3%83%87%E3%82%A3-%E3%82%AF%E3%83%AD%E3%82%B9%E3%83%88%E3%83%AC%E3%83%B3%E3%83%89/id265250079','Science & Technology','apple,spotify','science-technology','podcast','https://cloud.tareqitos.me/i/e112d3e0-72cb-42a2-88a1-577699e7ccbd.jpg'),
	('Still Rendering (スティレン)',208,'A couple in Brooklyn chats about life, tech, and culture.','https://blossomlink.me/still-rendering','Science & Technology','apple,spotify,youtube','science-technology','podcast','https://cloud.tareqitos.me/i/75b89b4c-50fb-46dc-b5fc-010873f7b8e8.jpg'),
	('Sonnai Rika no Jikan (そんない理科の時間)',209,'Friendly science episodes and curious everyday explanations.','https://sonnai.com/','Science & Technology','apple,spotify','science-technology','podcast','https://cloud.tareqitos.me/i/c4bb6a81-b7ba-4094-bbc2-3e164d78405f.jpg?width=200'),
	('Off Topic (オフトピック)',210,'US-centric tech, startups, business, and culture deep dives.','https://www.offtopic.jp/about','Science & Technology','apple,spotify,youtube','science-technology','podcast','https://cloud.tareqitos.me/i/8223d1b8-7edf-4d2c-b2ed-b8cd78a9e5ce.jpg'),
	('Yuru Computer Kagaku Radio (ゆるコンピュータ科学ラジオ)',211,'Easygoing computer science chats for curious listeners.','https://podcasts.apple.com/jp/podcast/%E3%82%86%E3%82%8B%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%82%BF%E7%A7%91%E5%AD%A6%E3%83%A9%E3%82%B8%E3%82%AA/id1604353315','Science & Technology','apple','science-technology','podcast','https://cloud.tareqitos.me/i/66adcf74-7bb4-41c9-8ca0-8e6b4c5d9b71.jpg'),
	('Scientalk (サイエントーク)',212,'Science made entertaining—news, topics, and fun explanations.','https://scien-talk.com/','Science & Technology','apple,spotify','science-technology','podcast','https://cloud.tareqitos.me/i/7319d659-92df-4417-b53c-282a3abc29ed.jpg'),
	('Radio Scientia (科学のラジオ〜Radio Scientia)',213,'Science conversations that connect research with daily life.','https://podcasts.apple.com/jp/podcast/%E7%A7%91%E5%AD%A6%E3%81%AE%E3%83%A9%E3%82%B8%E3%82%AA-radio-scientia/id1571226322','Science & Technology','apple','science-technology','podcast','https://cloud.tareqitos.me/i/616f5bb6-9bca-4b91-b804-c9371db159b3.jpg'),
	('Yuru Yuru Sugaku Essence (ゆるゆる数学エッセンス)',214,'Relaxed math stories and concepts, explained simply.','https://podcasts.apple.com/jp/podcast/%E3%82%86%E3%82%8B%E3%82%86%E3%82%8B%E6%95%B0%E5%AD%A6%E3%82%A8%E3%83%83%E3%82%BB%E3%83%B3%E3%82%B9/id1608689666','Science & Technology','apple','science-technology','podcast','https://cloud.tareqitos.me/i/c5df5f39-2504-4aa1-b7fe-d87a3596755b.jpg'),
	('Scienmania (サイエンマニア)',215,'Science curiosities, weird facts, and learning for fun.','https://podcasts.apple.com/us/podcast/%E3%82%B5%E3%82%A4%E3%82%A8%E3%83%B3%E3%83%9E%E3%83%8B%E3%82%A2/id1583760781','Science & Technology','apple','science-technology','podcast','https://cloud.tareqitos.me/i/05cfc743-99d2-4bf2-8dd4-5ee8ef68fbcb.jpg'),
	('Kieharu Psychology Radio (きえはる心理学ラジオ)',216,'Psychology explained in a calm, approachable way.','https://podcasts.apple.com/jp/podcast/%E3%81%8D%E3%81%88%E3%81%AF%E3%82%8B%E5%BF%83%E7%90%86%E5%AD%A6%E3%83%A9%E3%82%B8%E3%82%AA/id1582322296','Science & Technology','apple','science-technology','podcast','https://cloud.tareqitos.me/i/39c33294-c822-4bbc-b3e4-1689cdd5c197.jpg'),
	('Know Food Radio (KNOWフードラジオ〜知って味わう理科・社会。)',217,'Food through science and society—learn while you listen.','https://podcasts.apple.com/jp/podcast/know%E3%83%95%E3%83%BC%E3%83%89%E3%83%A9%E3%82%B8%E3%82%AA-%E7%9F%A5%E3%81%A3%E3%81%A6%E5%91%B3%E3%82%8F%E3%81%86%E7%90%86%E7%A7%91-%E7%A4%BE%E4%BC%9A/id1598116589','Science & Technology','apple','science-technology','podcast','https://cloud.tareqitos.me/i/cf4c2a53-edc4-4b0c-ac58-41f5737de801.jpg'),
	('Butuzaku (ぶつざく)',218,'Quick, friendly intros to living things and biology topics.','https://podcasts.apple.com/jp/podcast/%E7%94%9F%E7%89%A9%E3%82%92%E3%81%96%E3%81%A3%E3%81%8F%E3%82%8A%E7%B4%B9%E4%BB%8B%E3%81%99%E3%82%8B%E3%83%A9%E3%82%B8%E3%82%AA-%E3%81%B6%E3%81%A4%E3%81%96%E3%81%8F/id1591918352','Science & Technology','apple','science-technology','podcast','https://cloud.tareqitos.me/i/733fa4c4-876b-49d0-9464-8c8fb1847c8c.jpg'),
	('Tsukuba Univ Lab Side Story',219,'Behind-the-scenes stories from university labs and research.','https://podcasts.apple.com/us/podcast/%E7%AD%91%E6%B3%A2%E5%A4%A7%E5%AD%A6%E3%83%9D%E3%83%83%E3%83%89%E3%82%AD%E3%83%A3%E3%82%B9%E3%83%88-%E7%A0%94%E7%A9%B6%E5%AE%A4%E3%82%B5%E3%82%A4%E3%83%89%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AA%E3%83%BC/id1619227905','Science & Technology','apple','science-technology','podcast','https://cloud.tareqitos.me/i/4e6bd92c-5ae9-4cb1-8058-fce8aa3299e3.jpg'),
	('Shonou Radio (小農ラジオ)',220,'Organic farming, soil, compost, and practical agri talk.','https://podcasts.apple.com/jp/podcast/%E5%B0%8F%E8%BE%B2%E3%83%A9%E3%82%B8%E3%82%AA/id1481765269','Science & Technology','apple,spotify','science-technology','podcast','https://cloud.tareqitos.me/i/e6883849-e12b-4af9-b679-d398d94e28b0.jpg');

/*!40000 ALTER TABLE `resources` ENABLE KEYS */;
UNLOCK TABLES;