DROP TABLE IF EXISTS `resources`;

CREATE TABLE `resources` (
  `name` varchar(50) NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(140) NOT NULL,
  `link` varchar(300) NOT NULL,
  `category` varchar(50) NOT NULL,
  `platform` varchar(50) DEFAULT NULL,
  `slug` varchar(50) NOT NULL,
  `path` varchar(50) NOT NULL,
  `image` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

LOCK TABLES `resources` WRITE;
/*!40000 ALTER TABLE `resources` DISABLE KEYS */;

INSERT INTO `resources` (`name`, `id`, `description`, `link`, `category`, `platform`, `slug`, `path`, `image`)
VALUES
	('Bret Mayer\'\'s Kanji Resource',1,'Kanji resources for structured practice and lists.','http://www.bretmayer.com/kanji.html','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Genkoyoushi Paper Generator',2,'Create manuscript paper for kanji practice.','https://www.incompetech.com/graphpaper/genkoyoushi/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Hinoki Project',3,'Computational linguistics and vocabulary learning.','https://hinoki-project.org/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Japanese Graph',4,'Practice kanji and vocabulary with visualizations.','https://japanesegraph.com/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Kanji by Stroke Order',5,'Learn kanji stroke order through writing practice.','https://kanji.sljfaq.org/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Kanji Practice',6,'Interactive platform for kanji and vocabulary.','https://kanjipractice.com/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Kanjipedia',7,'Comprehensive kanji dictionary with examples.','https://www.kanjipedia.jp/howto/about.html','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Koohii Kanji Review',8,'Community-driven kanji and vocabulary learning.','https://kanji.koohii.com/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Kotoba no Gakko',9,'Vocabulary acquisition and insights.','https://site.kotobanogakko.com/special/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('KotobaBot',10,'Chatbot for practicing vocabulary.','https://kotobaweb.com/bot','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Kotowaza',11,'Learn proverbs and cultural insights.','https://kotowaza.co.uk/index.php','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Kurumi Kanji Search',12,'Kanji search tool to build vocabulary.','https://kurumi.com/jp/kjbh/?k=%E6%9C%AC','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Mainichi Kanji',13,'Daily kanji practice to build vocabulary.','https://mainichikanji.com/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Niai - Similar Vocabulary',14,'Explore similar words.','https://niai.mrahhal.net/similar','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Nippon Colors',15,'Traditional Japanese color meanings','https://nipponcolors.com/','Vocabulary & Kanji','','vocabulary','vocabulary',NULL),
	('OniKanji',16,'Master kanji naturally with context-based learning systeme','https://onikanji.com/','Vocabulary & Kanji','','vocabulary','vocabulary',NULL),
	('Shared Anki Decks',17,'Anki decks for vocabulary and kanji.','https://ankiweb.net/shared/info/457148655?cb=1717343711197','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('WaniKani',18,'Learn kanji and vocabulary with mnemonics.','https://www.wanikani.com/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Wikibooks Linguistics Vocabulary',19,'Vocabulary list for linguistics terms.','https://en.m.wikibooks.org/wiki/Japanese/Vocabulary/Linguistics','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('Yomikatawa',20,'Learn vocabulary and kanji readings.','https://yomikatawa.com/','Vocabulary & Kanji',NULL,'vocabulary','vocabulary',NULL),
	('DeepL Translator',21,'Accurate translations between languages.','https://www.deepl.com/en/translator#','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('GeekyDic',22,'User-friendly online dictionary.','https://emilekroeger.github.io/geekydic/app/index.html#/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Goo Dictionary',23,'Comprehensive dictionary with examples.','https://dictionary.goo.ne.jp/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Jisho',24,'Powerful dictionary with detailed explanations.','http://www.jisho.org/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Jisho (Hlorenzi)',25,'Alternative Jisho interface with added features.','https://jisho.hlorenzi.com/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Jitenon Kanji Dictionary',26,'Kanji dictionary with detailed character breakdowns.','https://kanji.jitenon.jp/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('JLect',27,'Explore dialects and regional vocabulary.','https://www.jlect.com/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Jotoba',28,'Multilingual dictionary with context.','https://jotoba.de/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Kanjisho',29,'Kanji-focused dictionary with readings and stroke order.','https://www.kanjisho.com/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Kotobank',30,'Dictionary aggregator with multiple sources.','https://kotobank.jp/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Onomato Project',31,'Explore onomatopoeia with examples.','https://onomatoproject.com/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('PokeJisho',32,'Pokémon-themed dictionary.','https://www.pokejisho.com/en/jisho/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Takoboto',33,'Offline dictionary with kanji lookup.','https://takoboto.jp/','Dictionaries',NULL,'dictionaries','applications',NULL),
	('Weblio Thesaurus',34,'Find synonyms and related words.','https://thesaurus.weblio.jp/','Dictionaries',NULL,'dictionaries','dictionaries',NULL),
	('Yomitan',35,'Translate text on webpages easily.','https://github.com/themoeway/yomitan','Dictionaries',NULL,'dictionaries','applications',NULL),
	('Aedict',36,'Comprehensive dictionary app.','http://aedict.eu/','Dictionaries',NULL,'dictionaries','applications',NULL),
	('Kanji Benkyō',37,'Learn kanji with this app.','https://apps.apple.com/us/app/learn-japanese-kanji-benky%C5%8D/id1541592138?ct=https%3A%2F%2Findiecatalog.app','Dictionaries',NULL,'dictionaries','applications',NULL),
	('Shirabe Jisho',38,'Dictionary app with kanji lookup.','https://apps.apple.com/app/shirabe-jisho/id1005203380','Dictionaries',NULL,'dictionaries','applications',NULL),
	('DJT Grammar Guide',39,'Extensive guide covering grammar in depth.','https://djtarchive.neocities.org/bunpou/full_day','Grammar',NULL,'grammar','grammar',NULL),
	('Edewakaru',40,'Detailed explanations of grammar points.','https://www.edewakaru.com/','Grammar',NULL,'grammar','grammar',NULL),
	('Guide to Japanese',41,'Your go-to guide for grammar and basics.','https://guidetojapanese.org/learn/','Grammar',NULL,'grammar','grammar',NULL),
	('IMABI',42,'Detailed grammar lessons for all levels.','https://www.imabi.org/','Grammar',NULL,'grammar','grammar',NULL),
	('JLPT Grammar List',43,'Comprehensive list of JLPT grammar points.','https://jlptgrammarlist.neocities.org/','Grammar',NULL,'grammar','grammar',NULL),
	('Kanji-Link',44,'Learn grammar and kanji with quizzes.','https://www.kanji-link.com/fr/#','Grammar',NULL,'grammar','grammar',NULL),
	('Maggie Sensei',45,'Friendly lessons on grammar points.','https://maggiesensei.com/','Grammar',NULL,'grammar','grammar',NULL),
	('Minato JF',46,'Online courses and resources, including grammar lessons.','https://minato-jf.jp/','Grammar',NULL,'grammar','grammar',NULL),
	('Sakubi',47,'Minimalist guide to essential grammar.','https://sakubi.neocities.org/','Grammar',NULL,'grammar','grammar',NULL),
	('Tanos JLPT Resources',48,'Grammar lists and practice materials for the JLPT.','http://www.tanos.co.uk/jlpt/','Grammar',NULL,'grammar','grammar',NULL),
	('Dokusho Club',49,'Reading club for learners.','https://dokushoclub.com/','Reading',NULL,'reading','reading',NULL),
	('Learn Natively',50,'Find books for your reading level.','https://learnnatively.com/','Reading',NULL,'reading','reading',NULL),
	('Mangaz',51,'Read manga online.','https://www.mangaz.com/','Reading',NULL,'reading','reading',NULL),
	('Master List of Book Clubs',52,'A master list of books going from absolute beginner to advanced learner','https://community.wanikani.com/t/master-list-of-book-clubs/35283','Reading',NULL,'reading','reading',NULL),
	('Satori Reader',53,'Read and listen to stories.','https://www.satorireader.com/','Reading',NULL,'reading','reading',NULL),
	('Sōseki Project',54,'A collection of the author Natsume Sōseki\'\'s work.','https://www.sosekiproject.org/#','Reading','','reading','reading',NULL),
	('Tadoku',55,'Free graded readers for learners.','https://tadoku.org/japanese/en/free-books-en/','Reading',NULL,'reading','reading',NULL),
	('Yomimono Ippai',56,'Lots of books to read for every level','http://www17408ui.sakura.ne.jp/tatsum/project/Yomimono/Yomimono-ippai/index.html','Reading',NULL,'reading','reading',NULL),
	('YomuJP',57,'Read texts with translations.','https://yomujp.com/','Reading',NULL,'reading','reading',NULL),
	('YomuYomu',58,'Read books online.','https://yomuyomu.app/','Reading',NULL,'reading','reading',NULL),
	('Manabi Reader',59,'A solid app for reading sentences, read ebooks and listen to audios.','https://reader.manabi.io/','Apps',NULL,'reading','reading',NULL),
	('Mihon',60,'Manga reader app.','https://mihon.app/','Apps',NULL,'reading','reading',NULL),
	('Voracious',61,'Improve reading and listening skills.','https://voracious.app/','Apps',NULL,'reading','reading',NULL),
	('Free Japanese Font',62,'Download free fonts.','https://www.freejapanesefont.com/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Google Sheets JLPT',63,'Comprehensive JLPT study resources.','https://docs.google.com/spreadsheets/d/15ELElkomfixdS4-dNrpxrNl14mlJUZrdD0h7N6iEE2k/edit?gid=1386920750#gid=1386920750','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Japanese Discord',64,'Join the community for language practice.','https://discord.gg/japanese','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Japanese Wiki',65,'Explore various topics.','https://www.japanesewiki.com/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Kaiwa Kai',66,'Practice conversation skills.','https://www.kaiwakai.com/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Kuzuri Resources',67,'Collection of useful resources.','https://kuzuri.neocities.org/resources','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('LangPractice',68,'Language practice platform.','https://langpractice.com/japanese/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Learn Japanese Reddit',69,'Community for learners.','https://www.reddit.com/r/LearnJapanese/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Rondely English Terms',70,'Glossary of English terms.','https://rondely.com/EigoYogo/irir/iti.htm','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('SuperNative',71,'Improve listening skills.','https://supernative.tv/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('The Moe Way',72,'An amazing guide with tips ','https://learnjapanese.moe/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Unagibun JLPT Online',73,'Online resources for JLPT preparation.','https://www.unagibun.com/jlpt-online/','Miscellaneous',NULL,'miscellaneous','miscellaneous',NULL),
	('Kana Dojo',74,'KanaDojo is a fun, minimalist, aesthetic platform for learning and practicing Japanese online','https://kanadojo.com','Kana',NULL,'kana','vocabulary',NULL),
	('Kana Pro',75,'Practice your hiragana and katakana','https://kana.pro','Kana',NULL,'kana','vocabulary',NULL),
	('Real Kana',76,'Study your kana with the possibility to choose between multiple fonts','https://realkana.com','Kana',NULL,'kana','vocabulary',NULL),
	('Akane Japanese Class',77,'Effective and beginner-friendly Japanese lessons.','https://www.youtube.com/@Akane-JapaneseClass/','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/d85bb43d-a668-413f-83ad-d22693f02a03.jpg'),
	('CI Japanese',78,'Comprehensible input for Japanese learners.','https://www.youtube.com/@cijapanese','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/e0f45662-ec4d-4a04-b1df-773ec6429768.jpg'),
	('Dogen',79,'Japanese language learning with a comedic twist.','https://www.youtube.com/@Dogen','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/76399ea0-eed3-420a-b11b-dfa84d7959e8.jpg'),
	('Japanese Ammo with Misa',80,'Comprehensive Japanese lessons for all levels.','https://www.youtube.com/@JapaneseAmmowithMisa','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/9eeba09f-98d3-486a-b53d-cdc75f63856b.jpg'),
	('Japanese with Shun',81,'Simple and effective Japanese language lessons.','https://www.youtube.com/@JapanesewithShun','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/6b8aeee9-f179-4019-a4b0-98ee7cdfd717.jpg'),
	('Japanese with Taka',82,'Master Japanese with Taka\'\'s focused lessons.','https://www.youtube.com/@JapanesewithTaka','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/21c8daac-3bde-4c2d-9aff-ba471a35d9ba.jpg'),
	('Japasuta',83,'Interactive Japanese language tutorials.','https://www.youtube.com/@japasuta','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/c2ecabe8-e935-4158-adf2-cdf3bb58f21a.jpg'),
	('Meshclass',84,'Learn Japanese through fun and interactive lessons.','https://www.youtube.com/@meshclass','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/4025ac12-6487-4f3d-9ffe-5dd6d284cabf.jpg'),
	('Miku Real Japanese',85,'Practical and real-life Japanese learning.','https://www.youtube.com/@mikurealjapanese','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/02649d85-7886-40fc-92f3-46ab25bf4189.jpg'),
	('Necota\'\'s Japanese Language Class',86,'Creative lessons for mastering Japanese.','https://www.youtube.com/@necotasjapaneselanguagecla291','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/e7c82a95-198f-43bc-bb59-3228fe942d9a.jpg'),
	('Nihongo no Mori',87,'Learn Japanese grammar and vocabulary effectively.','https://www.youtube.com/@nihongonomori2013','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/5331a389-d720-4097-9f31-9e0f201b38e0.jpg'),
	('Onomappu',88,'Learn Japanese through natural expressions and phrases.','https://www.youtube.com/@Onomappu/','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/26d78526-5f7a-42ed-8fb5-6a39b020cb45.jpg'),
	('Sambonjuku',89,'Fun and engaging Japanese lessons for learners.','https://www.youtube.com/@sambonjuku/','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/51c7e587-a8db-4814-9e36-78762f5cf9e6.jpg'),
	('Sayuri Saying',90,'Practical and fun Japanese language tutorials.','https://www.youtube.com/@SayuriSaying','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/a879e1a3-5439-4d6d-8d60-e161c571023c.jpg'),
	('Tanaka San',91,'Learn Japanese with practical conversations and tips.','https://www.youtube.com/@japanese_tanakasan','Language Learning','youtube','language-learning','media','https://cloud.tareqitos.me/i/5aeb279c-b4b8-4b8a-8fef-3c57befb642e.jpg'),
	('Archipel Documentaries',92,'Deep dive into Japanese culture and tradition through documentaries.','https://www.youtube.com/@ArchipelDocumentaries','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/f59e9b0c-fc9e-492e-b49f-116f334bdf92.jpg'),
	('Bappa Shota',93,'Japanese vlogger who has been traveling the world since 2011','https://www.youtube.com/@BappaShota','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/a27c10e8-0058-4859-ac19-aeccaf37c764.jpg?height=150&width=150'),
	('Koto Labo',94,'Insights into Japanese music and traditional instruments.','https://www.youtube.com/@kotolabo','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/b6d30567-06bd-4d00-8254-976d74e9dad8.jpg'),
	('Osho Taigu',95,'Explore Japanese traditions and Zen teachings.','https://www.youtube.com/@osho_taigu/','Culture','youtube','culture','media','https://cloud.tareqitos.me/i/be5a1326-fc18-4f04-9c11-ff386428d6d7.jpg'),
	('Burihhiiinews Channel',96,'Stay updated with Japanese news and cultural insights.','https://www.youtube.com/@burihhiiiinewschannel','Entertainment','youtube','entertainment','media','https://cloud.tareqitos.me/i/f58c21eb-c837-42f9-af41-ef9afd6d38b2.jpg'),
	('Cocoro Kase',97,'Engaging lessons and insights focused on language and cultural nuances.','https://www.youtube.com/@cocoro_kase','Pop Culture','youtube','pop-culture','media','https://cloud.tareqitos.me/i/dd11fcff-2253-4d1d-8e0b-2eef1a9b2493.jpg'),
	('EASY JAPANESE',98,'Simplified and accessible language lessons with practical examples.','https://www.youtube.com/@EASYJAPANESE','Podcast','youtube','podcast','media','https://cloud.tareqitos.me/i/97cf5176-be71-4a56-9c47-e3cf3fbae773.jpg'),
	('Nihongo Con Teppei',99,'Podcast for beginner on how to speak the language naturally.','https://open.spotify.com/show/4W4jYoKRmjlURKO1fIfcOK?si=53534ca1bd654ffd','Podcast','spotify','podcast','media','https://cloud.tareqitos.me/i/f5d98ed5-9d5d-40a7-823d-81e11f6758bf.jpg?height=100&width=100&quality=50'),
	('Oyasumi Japanese with Shun',100,'Easy Japanese using Genki (N5-N4) grammar. This is perfect to listen before you go to sleep.','https://open.spotify.com/show/7x4JCyDeWR60kzJXoOBTrQ','Podcast','spotify','podcast','media','https://cloud.tareqitos.me/i/10d34001-1ee0-4773-9c50-5e170a519a82.jpg?height=150&width=150'),
	('The Bite Size Japanese Podcast',101,'A podcast about daily life for improving your listening skills','https://open.spotify.com/show/58H68tM3uC2JNZI4hXvdeu','Podcast','spotify','podcast','media','https://cloud.tareqitos.me/i/6a10d710-6f8c-41c4-b36e-384784a08748.jpg?height=150&width=150'),
	('The Miku Real Japanese',102,'Miku shares insights into daily life and culture.','https://open.spotify.com/show/6Nl8RDfPxsk4h4bfWe76Kg?si=48aec8e2d5234a98','Podcast','spotify','podcast','media','https://cloud.tareqitos.me/i/d945d521-c56f-43da-972a-8386260670f2.jpg?height=150&width=150'),
	('Game Nantoka / ゲームなんとか',103,'Podcast of friends casually talking about games.','https://open.spotify.com/show/0VpJSbTokWLLJ0zppnbrlM?si=13ab080d6e7f4dbe','Gaming','spotify','gaming','media','https://cloud.tareqitos.me/i/1a81d385-dfca-40da-aea0-5133f3c1beac.jpg?height=150&width=150'),
	('KIYOi / キヨ。',104,'Dynamic gaming streams, reviews, and humorous commentary.','https://www.youtube.com/@KIYOisGOD','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/80e37a5c-f9b4-4f6d-b479-4391cffc8511.jpg'),
	('Kojiseto Games',105,'Entertaining gaming content with commentary on various popular titles.','https://www.youtube.com/@KojisetoGames','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/c18df950-aea4-47df-8422-dbcccb81a605.jpg'),
	('Senakuma Desu',106,'Fun and creative videos that explore casual and everyday topics.','https://www.youtube.com/@senakumadesu','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/cfc78559-4f1a-4c53-8995-241d879052bd.jpg'),
	('Sora Sakurai',107,'Official channel of Masahiro Sakurai, creator of Kirby and Super Smash Bros.','https://www.youtube.com/@sora_sakurai_jp','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/468ce1be-a0cd-499b-949f-03b3ce7930b0.jpg'),
	('Tetsuo/てつお ',108,'Channel focused on the Dragon Quest video games series.','https://www.youtube.com/@ch-mj8xi','Gaming','youtube','gaming','media','https://cloud.tareqitos.me/i/b1d092f6-3ede-4c1b-8da5-f89bad292a32.jpg'),
	('Anki',109,'Powerful flashcard app for studying.','https://apps.ankiweb.net/','Flashcards',NULL,'flashcards','applications',NULL),
	('Quizlet',110,'Study with flashcards and games.','https://quizlet.com/','Flashcards',NULL,'flashcards','applications',NULL),
	('Renshuu',111,'Practice vocabulary and grammar.','https://www.renshuu.org/','Flashcards',NULL,'flashcards','applications',NULL),
	('Ringotan',112,'Learn kanji with mnemonics.','https://www.ringotan.com/','Flashcards',NULL,'flashcards','applications',NULL),
	('Smouldering Durtles',113,'An android client application for WaniKani','https://play.google.com/store/apps/details?id=com.smouldering_durtles.wk&hl=en-US','Flashcards',NULL,'flashcards','applications',NULL),
	('Bunpro',114,'Grammar study platform.','https://bunpro.jp/','Grammar & Kana',NULL,'grammar-kana','applications',NULL),
	('Kana',115,'Learn hiragana and katakana.','https://apps.apple.com/us/app/kana-hiragana-and-katakana/id1454200955?ct=https%3A%2F%2Findiecatalog.app','Grammar & Kana',NULL,'grammar-kana','applications',NULL),
	('Genkoyoushi',116,'Japanese character graph generator','https://www.incompetech.com/graphpaper/genkoyoushi/','Tools',NULL,'tools','applications',NULL),
	('Hanabi',117,'A powerful subtitle parser for Youtube using AI','https://hanabira.org/','Tools',NULL,'tools','applications',NULL),
	('Jimaku',118,'A list of subtitles files for anime, drama and movies.','https://jimaku.cc','Tools',NULL,'tools','applications',NULL),
	('Kaku',119,'Handwriting recognition app.','https://kaku.fuwafuwa.ca/','Tools',NULL,'tools','applications',NULL),
	('Sensei',120,'Learn with interactive lessons.','https://apps.apple.com/us/app/learn-japanese-sensei/id1495789984?ct=https%3A%2F%2Findiecatalog.app','Tools',NULL,'tools','applications',NULL),
	('AFK Arena',121,'Adventure / Arena game','https://play.google.com/store/apps/details?id=com.lilithgame.hgame.gp','Mobile','','mobile','games',NULL),
	('Aggretsuko: Match 3',122,'Puzzle game based on the popular Netflix animation series','https://play.google.com/store/apps/details?id=com.hive.aggretsuko','Mobile','','mobile','games',NULL),
	('ALTER EGO',123,'Game about literature and psychology','https://play.google.com/store/apps/details?id=com.caracolu.alterego','Mobile','','mobile','games',NULL),
	('Animal crossing: Pocket Camp',124,'Build your camp with furnitures','https://play.google.com/store/apps/details?id=com.nintendo.zaca','Mobile','','mobile','games',NULL),
	('Any Kairosoft game',125,'Strategy game in a RPG style','https://play.google.com/store/apps/dev?id=7710637777904825280','Mobile','','mobile','games',NULL),
	('AZNANA',126,'Narrative game','https://play.google.com/store/apps/details?id=com.caracolu.aznana','Mobile','','mobile','games',NULL),
	('BanG Dream!',127,'Popular rythm game with original and anime covered songs','https://play.google.com/store/apps/details?id=com.bushiroad.en.bangdreamgbp','Mobile','','mobile','games',NULL),
	('Bear\'\'s Restaurant',128,'Manage a restaurant for the dead people and animals','https://play.google.com/store/apps/details?id=com.rpgsnack.bearsrestaurant','Mobile','','mobile','games',NULL),
	('Cats & Soup',129,'Cook with cats and prepare delicious soups','https://play.google.com/store/apps/details?id=com.hidea.cat','Mobile','','mobile','games',NULL),
	('Fishing paradiso',130,'A narrative game with a moving scenario','https://play.google.com/store/apps/details?id=com.rpgsnack.fishingparadise','Mobile','','mobile','games',NULL),
	('her tears were my light',131,'A love story between time and space','https://play.google.com/store/apps/details?id=com.nomnomnami.hertearsweremylight','Mobile','','mobile','games',NULL),
	('Hungry hearts diner',132,'Manage a Japanese restaurant and bond with your clients','https://play.google.com/store/apps/details?id=jp.co.gagex.orionEN','Mobile','','mobile','games',NULL),
	('Love is in small things',133,'A cozy art game','https://play.google.com/store/apps/details?id=com.lunosoft.puuung1','Mobile','','mobile','games',NULL),
	('Snowman Story',134,'Follow the story of a snowman who doesn\'\'t want to melt','https://play.google.com/store/apps/details?id=com.rpgsnack.snowman','Mobile','','mobile','games',NULL),
	('Sumikkogurashi farm',135,'Relaxing farming game','https://play.google.com/store/apps/details?id=jp.co.imagineer.sumikkogurashi.farm','Mobile','','mobile','games',NULL),
	('Tsuki\'\'s Oddysey',136,'A passive adventure game','https://play.google.com/store/apps/details?id=com.hyperbeard.odyssey','Mobile','','mobile','games',NULL),
	('Vanished anniversary',137,'Visual novel with five unique stories','https://play.google.com/store/apps/details?id=com.abocado.abocado','Mobile','','mobile','games',NULL),
	('ねこあつめ',138,'Tamagochi game with a cat','https://play.google.com/store/apps/details?id=jp.co.hit_point.nekoatsume','Mobile','','mobile','games',NULL),
	('旅かえる',139,'A game about a Frog that goes on many journeys','https://play.google.com/store/apps/details?id=jp.co.hit_point.tabikaeru','Mobile','','mobile','games',NULL),
	('unityroom',140,'A list of Unity-made games playable in browser','https://unityroom.com/','Web','','web','games',NULL);

/*!40000 ALTER TABLE `resources` ENABLE KEYS */;
UNLOCK TABLES;